name: Android Build

on:
    push:
        branches:
            - "**"
    pull_request:
    workflow_call:
        outputs:
            artifact_name:
                description: Android artifact name
                value: ${{ jobs.build.outputs.artifact_name }}
            artifact_file:
                description: Android artifact filename
                value: ${{ jobs.build.outputs.artifact_file }}

jobs:
    build:
        runs-on: ubuntu-latest
        outputs:
            artifact_name: ${{ steps.prepare.outputs.artifact_name }}
            artifact_file: ${{ steps.prepare.outputs.artifact_file }}

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up Java
              uses: actions/setup-java@v4
              with:
                  distribution: temurin
                  java-version: "17"

            - name: Set up Android SDK
              uses: android-actions/setup-android@v3

            - name: Gradle cache
              uses: gradle/actions/setup-gradle@v3
              continue-on-error: true

            - name: Grant execute permission for gradlew
              run: chmod +x android/gradlew

            - name: Build release APK
              working-directory: android
              run: ./gradlew :app:assembleRelease --stacktrace --no-daemon

            - name: Prepare Android artifact
              id: prepare
              run: |
                  RELEASE_APK="android/app/build/outputs/apk/release/puppybot-release-unsigned.apk"
                  test -f "$RELEASE_APK"
                  mkdir -p artifacts
                  cp "$RELEASE_APK" "artifacts/puppybot.apk"
                  echo "artifact_name=puppybot-android" >> "$GITHUB_OUTPUT"
                  echo "artifact_file=puppybot.apk" >> "$GITHUB_OUTPUT"

            - name: Upload APK artifact
              uses: actions/upload-artifact@v4
              with:
                  name: ${{ steps.prepare.outputs.artifact_name }}
                  path: artifacts/puppybot.apk
                  if-no-files-found: error
                  retention-days: 14
