name: Android CI & Release

on:
    push:
        branches:
            - "**"
        tags:
            - "*"
    pull_request:

permissions:
    contents: write

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up Java
              uses: actions/setup-java@v4
              with:
                  distribution: temurin
                  java-version: "17"

            - name: Set up Android SDK
              uses: android-actions/setup-android@v3

            # (Optional) Speed up builds
            - name: Gradle cache
              uses: gradle/actions/setup-gradle@v3
              continue-on-error: true

            - name: Grant execute permission for gradlew
              run: chmod +x android/gradlew

            - name: Build release APK
              working-directory: android
              run: ./gradlew :app:assembleRelease --stacktrace --no-daemon

            - name: Prepare artifact
              run: |
                  RELEASE_APK="android/app/build/outputs/apk/release/puppybot-release-unsigned.apk"
                  test -f "$RELEASE_APK"
                  mkdir -p dist
                  cp "$RELEASE_APK" "dist/puppybot.apk"

            # Always upload the build output as a CI artifact (visible on the run page)
            - name: Upload CI artifact
              uses: actions/upload-artifact@v4
              with:
                  name: puppybot.apk
                  path: dist/puppybot.apk
                  if-no-files-found: error
                  retention-days: 14

            # Only on tag pushes: create/update a Release and attach the APK
            - name: Create/Update GitHub Release (tag pushes only)
              if: startsWith(github.ref, 'refs/tags/')
              uses: softprops/action-gh-release@v2
              with:
                  tag_name: ${{ github.ref_name }}
                  name: ${{ github.ref_name }}
                  generate_release_notes: true
                  files: dist/puppybot.apk
